【发现已存在的游戏窗口】
正在返回菜单,请保持游戏画面处于前台
【现在处于主菜单】
【目标出现】images/battery.png 置信度是：0.9999998211860657
Using CPU. Note: This module is much faster with a GPU.
当前电量为：72 
任务开始，执行 0 次循环
WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 747, in run
    lottery()
    ~~~~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 437, in lottery
    menu('leave')
    ~~~~^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 190, in menu
    pydirectinput.press('esc', )
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 243, in wrapper
    _handlePause(funcArgs.get("_pause"))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 232, in _handlePause
    time.sleep(PAUSE)
    ~~~~~~~~~~^^^^^^^
KeyboardInterrupt

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 747, in run
    lottery()
    ~~~~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 437, in lottery
    menu('leave')
    ~~~~^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 190, in menu
    pydirectinput.press('esc', )
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 243, in wrapper
    _handlePause(funcArgs.get("_pause"))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 232, in _handlePause
    time.sleep(PAUSE)
    ~~~~~~~~~~^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 768, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 765, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
