【发现已存在的游戏窗口】
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
【现在处于主菜单】
Using CPU. Note: This module is much faster with a GPU.
当前电量为：308 
任务开始，执行 3 次循环
【现在处于主菜单】
【目标出现】images/lobby.png 置信度是：1.0
【目标出现】images/tactics.png 置信度是：0.9978101849555969
【1】等待目标中 images/train.png
【2】等待目标中 images/train.png
【3】等待目标中 images/train.png
【4】等待目标中 images/train.png
【5】等待目标中 images/train.png
【6】等待目标中 images/train.png
【7】等待目标中 images/train.png
【8】等待目标中 images/train.png
【9】等待目标中 images/train.png
【10】等待目标中 images/train.png
【11】等待目标中 images/train.png
【12】等待目标中 images/train.png
【13】等待目标中 images/train.png
【14】等待目标中 images/train.png
【15】等待目标中 images/train.png
【16】等待目标中 images/train.png
【17】等待目标中 images/train.png
【18】等待目标中 images/train.png
【19】等待目标中 images/train.png
【20】等待目标中 images/train.png
--------等待超时,开始重试--------
【重试超时】任务在某一步失败，请检查日志
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 696, in run
    os.rename(f"logs/{timestamp_instance.timestamp}.txt", f'logs/【超时】{timestamp_instance.timestamp}.txt')
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'logs/2025-04-26 16.09.59.txt' -> 'logs/【超时】2025-04-26 16.09.59.txt'

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 696, in run
    os.rename(f"logs/{timestamp_instance.timestamp}.txt", f'logs/【超时】{timestamp_instance.timestamp}.txt')
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'logs/2025-04-26 16.09.59.txt' -> 'logs/【超时】2025-04-26 16.09.59.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 708, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 705, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
KeyboardInterrupt
